[project]
name = "ai-agent-oil-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "ruff>=0.11.4",
    "streamlit>=1.44.1",
]
